name 'tw-foundation'
maintainer 'Geoff Gerrietts'
maintainer_email 'geoff@gerrietts.net'
license 'MIT'
description 'Establishes a nice foundation for wreckstations.'
long_description 'Installs a variety of important packages.'
version '0.1.0'

depends 'poise-python', '~> 1.2.1'
depends 'apt', '~> 2.9.2'
depends 'firewall', '~> 2.4.0'
